// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetProductByName struct {
	Name string `json:"name"`
}

type NewProduct struct {
	Name   string  `json:"name"`
	Model  string  `json:"model"`
	Price  float64 `json:"price"`
	Amount int     `json:"amount"`
}

type Product struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Model  string  `json:"model"`
	Price  float64 `json:"price"`
	Amount int     `json:"amount"`
}
